[package]
name = "jrm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
jrm-macro = { path = "../jrm-macro", features = ["debug"] }
maplit = "1.0.2"
