[package]
name = "jrm-parse"
version = "0.1.0"
edition = "2024"

[dependencies]
jrm-macro = { path = "../jrm-macro", features = ["debug"] }
anyhow = { workspace = true }
maplit = "1.0.2"
bitflags = "2.9.1"

[features]
default = []
test = []
